linters:
    enable:
        - asciicheck
        - bodyclose
        - durationcheck
        - errname
        - errorlint
        - exhaustive
        - exportloopref
        - forcetypeassert
        - goimports
        - gosec
        - makezero
        - misspell
        - nakedret
        - nilerr
        - noctx
        - nolintlint
        - nosprintfhostport
        - predeclared
        - revive
        - tagliatelle
        - unconvert
        - unparam
        - wastedassign
        - staticcheck
        - govet

linters-settings:
    revive:
        rules:
            - name: unused-parameter
              disabled: true
    exhaustive:
        default-signifies-exhaustive: true
    gosec:
        excludes:
            - G401
            - G501
            - G115
            - G406
            - G506
    misspell:
        ignore-words:
            # elf RELA
            - rela
            - equalisation
            - synchronisation
    govet:
        enable-all: true
        disable:
            - fieldalignment
            - shadow
    staticcheck:
        checks: ["all"]

run:
    timeout: 5m
    skip-dirs:
        # allow md5
        - dev
        - doc
        # ignore warnings in code from crypto/tls and zmap/zcrypto
        - format/tls/tlsdecrypt
